LIBC_OBJ+=stdio/iotab.o      \
	  stdio/fopen.o      \
	  stdio/fdopen.o     \
	  stdio/fgetc.o      \
	  stdio/fgets.o      \
	  stdio/fputc.o      \
	  stdio/fputs.o      \
	  stdio/fread.o      \
	  stdio/fwrite.o     \
	  stdio/fseek.o	     \
	  stdio/fflush.o     \
	  stdio/fclose.o     \
	  stdio/ungetc.o     \
	  stdio/printf.o     \
	  stdio/fprintf.o    \
	  stdio/sprintf.o    \
	  stdio/snprintf.o   \
	  stdio/vsprintf.o   \
	  stdio/vsnprintf.o  \
	  stdio/perror.o