LIBC_OBJ+=unistd/getuid.o \
          unistd/setuid.o \
	  unistd/setsid.o \
	  unistd/mknod.o \
          unistd/errno.o \
	  unistd/open.o \
	  unistd/read.o \
	  unistd/stat.o \
	  unistd/link.o \
	  unistd/execl.o \
	  unistd/execv.o \
	  unistd/execle.o \
          unistd/execve.o \
          unistd/execvp.o \
          unistd/execlp.o \
	  unistd/_exit.o \
	  unistd/sbrk.o \
          unistd/fork.o \
	  unistd/getpid.o  \
	  unistd/chdir.o \
	  unistd/close.o \
	  unistd/sync.o \
	  unistd/mkdir.o \
	  unistd/write.o \
	  unistd/fstat.o \
	  unistd/dup.o  \
	  unistd/dup2.o \
	  unistd/fcntl.o \
	  unistd/lseek.o \
	  unistd/wait.o \
	  unistd/waitpid.o \
	  unistd/pipe.o \
	  unistd/execl.o \
	  unistd/rmdir.o \
	  unistd/unlink.o \
	  unistd/mount.o  \
	  unistd/umount.o \
	  unistd/sigsend.o \
	  unistd/sigmask.o \
	  unistd/sigact.o  \
	  unistd/times.o   \
	  unistd/pause.o   \
	  unistd/gettimeofday.o \
	  unistd/settimeofday.o \
	  unistd/fchdir.o       \
	  unistd/getcwd.o  \
	  unistd/ioctl.o  \
	  unistd/chmod.o 
	  
