#/* This file is part of The Firekylin Operating System.
# *
# * Copyright (c) 2016, Liuxiaofeng
# * All rights reserved.
# *
# * This program is free software; you can distribute it and/or modify
# * it under the terms of The BSD License, see LICENSE.
# */

lib:
	make -C csu
	make -C libc
	make -C libm

clean: 
	make clean -C csu
	make clean -C libc
	make clean -C libm
