LIBC_OBJ+=ctype/__ctype.o \
          ctype/isalnum.o \
	  ctype/isalpha.o \
	  ctype/iscntrl.o \
          ctype/isdigit.o \
	  ctype/islower.o \
	  ctype/isprint.o \
	  ctype/ispuntc.o \
          ctype/isupper.o \
	  ctype/isxdigit.o \
	  ctype/isspace.o  \
	  ctype/isgraph.o \
	  ctype/isascii.o \
          ctype/tolower.o \
	  ctype/toupper.o \
	  ctype/toascii.o  \
	  ctype/iswalnum.o \
	  ctype/iswalpha.o \
	  ctype/iswcntrl.o \
          ctype/iswdigit.o \
	  ctype/iswlower.o \
	  ctype/iswprint.o \
	  ctype/iswpuntc.o \
          ctype/iswupper.o \
	  ctype/iswxdigit.o \
	  ctype/iswspace.o  \
	  ctype/iswgraph.o \
          ctype/towlower.o \
	  ctype/towupper.o 