LIBC_OBJ+=stdlib/abort.o   \
          stdlib/abs.o     \
	  stdlib/atexit.o  \
	  stdlib/atoi.o    \
	  stdlib/atol.o    \
	  stdlib/bsearch.o \
	  stdlib/exit.o    \
	  stdlib/getenv.o  \
	  stdlib/malloc.o  \
	  stdlib/rand.o    \
	  stdlib/realloc.o \
	  stdlib/calloc.o  \
	  stdlib/raise.o   \
	  stdlib/setjmp.o  \
	  stdlib/strtol.o  \
	  stdlib/strtoll.o \
	  stdlib/strtoul.o \
	  stdlib/strtoull.o \
	  stdlib/strtof.o    \
	  stdlib/strtod.o    \
	  stdlib/strtold.o   \
	  stdlib/putenv.o    \
	  stdlib/div.o      \
	  stdlib/ldiv.o     \
	  stdlib/qsort.o    \
	  stdlib/system.o   \
	  stdlib/setenv.o   